name: CI Pipeline

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Lint staged frontend files
        run: cd frontend && npx lint-staged

      - name: Install backend dependencies
        run: cd backend && npm install

      - name: Lint staged backend files
        run: cd backend && npx lint-staged

  build:
    runs-on: self-hosted
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Build frontend
        run: cd frontend && npm run build

      - name: Install backend dependencies
        run: cd backend && npm install

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Install backend dependencies
        run: cd backend && npm install

      - name: Run backend tests
        run: cd backend && npm test -- --coverage

      # Sauvegarde du coverage si nÃ©cessaire
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage
          path: backend/coverage

  sonarcloud:
    name: SonarCloud Scan & Quality Gate
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Install Backend Dependencies
        run: cd backend && npm install

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        with:
          args: >
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.projectKey=mathyscxsl_CloudNativeApplicationCurse
            -Dsonar.organization=mathyscxsl
            -Dsonar.sources=backend/src
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}

      - name: SonarCloud Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@cf038b0e0cdecfa9e56c198bbb7d21d751d62c3b
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}